stages:
  - validate
  - plan
  - apply
  - destroy


.base:
  image:
    name: hashicorp/terraform
    entrypoint: [""]
  before_script:
    - terraform init

terraformValidate:
  extends: .base
  stage: validate
  script:
    - terraform validate

terraformPlan:
  extends: .base
  stage: plan
  script:
    - terraform plan -out=plan.out
  cache:
    key: plan
    policy: push
    paths:
      - plan.out

terraformApply:
  extends: .base
  stage: apply
  script:
    - terraform apply plan.out
  cache:
    key: plan
    policy: pull
    paths:
      - plan.out
  when: manual
  environment:
    name: apply_ci
    on_stop: terraformDestroy
    auto_stop_in: 5 min

terraformDestroy:
  extends: .base
  stage: destroy
  script:
    - terraform destroy -auto-approve
  when: manual
  environment:
    name: apply_ci
    action: stop
